version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@01.3.0

jobs:
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd terraform &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd terraform &&
            terraform apply -auto-approve -var="ecr_image_tag=${CIRCLE_SHA1}"

workflows:
  main:
    jobs:
      - aws-ecr/build-and-push-image:
          context: TerraformContext
          repo: "${TF_VAR_service_name}"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          aws-access-key-id: TF_VAR_aws_provider_key
          aws-secret-access-key: TF_VAR_aws_provider_secret
          account-url: TF_VAR_aws_ecr_account_url
          filters:
            branches:
              only:
                - master
                - qa
                - feature/NewTypeDeploy
      - infrastructure-providing-and-deploy:
          context: 
            - TerraformContext
          requires: 
            - aws-ecr/build-and-push-image